/*package Pcanteen.Backend.dto;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class PriceHistoryDTO {
    private Double price;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    private Boolean wasActive;
    private LocalDateTime createdAt;
    private String createdBy;

    // Constructors, getters, and setters are automatically generated by @Data
    // But we'll include them explicitly for clarity

    public PriceHistoryDTO() {
    }

    public PriceHistoryDTO(Double price, LocalDateTime startDate, LocalDateTime endDate, 
                         Boolean wasActive, LocalDateTime createdAt, String createdBy) {
        this.price = price;
        this.startDate = startDate;
        this.endDate = endDate;
        this.wasActive = wasActive;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public LocalDateTime getStartDate() {
		return startDate;
	}

	public void setStartDate(LocalDateTime startDate) {
		this.startDate = startDate;
	}

	public LocalDateTime getEndDate() {
		return endDate;
	}

	public void setEndDate(LocalDateTime endDate) {
		this.endDate = endDate;
	}

	public Boolean getWasActive() {
		return wasActive;
	}

	public void setWasActive(Boolean wasActive) {
		this.wasActive = wasActive;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
    // All getters and setters are included via @Data
    
}*/

// PriceHistoryDTO.java
package Pcanteen.Backend.dto;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class PriceHistoryDTO {
    private Long id;
    private String menuId;
    private String name;
    private String category;
    private Double price;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    private Boolean isActive;
    private LocalDateTime createdAt;
    private String createdBy;
    private Boolean availableStatus;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getMenuId() {
		return menuId;
	}
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public Double getPrice() {
		return price;
	}
	public void setPrice(Double price) {
		this.price = price;
	}
	public LocalDateTime getStartDate() {
		return startDate;
	}
	public void setStartDate(LocalDateTime startDate) {
		this.startDate = startDate;
	}
	public LocalDateTime getEndDate() {
		return endDate;
	}
	public void setEndDate(LocalDateTime endDate) {
		this.endDate = endDate;
	}
	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Boolean getAvailableStatus() {
		return availableStatus;
	}
	public void setAvailableStatus(Boolean availableStatus) {
		this.availableStatus = availableStatus;
	}
	public PriceHistoryDTO(Long id, String menuId, String name, String category, Double price, LocalDateTime startDate,
			LocalDateTime endDate, Boolean isActive, LocalDateTime createdAt, String createdBy,
			Boolean availableStatus) {
		super();
		this.id = id;
		this.menuId = menuId;
		this.name = name;
		this.category = category;
		this.price = price;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isActive = isActive;
		this.createdAt = createdAt;
		this.createdBy = createdBy;
		this.availableStatus = availableStatus;
	}
	public PriceHistoryDTO() {
		super();
		// TODO Auto-generated constructor stub
	}

    // Constructors, getters and setters are handled by @Data
    
    
}